// Bad way of including all of the images...
#include "ball.h"
#include "blox.h"
#include "world_tex.h"
#include "cobblebrick.h"
#include "box.h"
#include "bullet.h"
#include "cursor.h"
#include "shadow.h"
#include "spinning_thonk.h"